version: '3.0'
services:
  minio:
    image: minio/minio:RELEASE.2022-12-07T00-56-37Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9002:9002" # 访问页面创建access key
    restart: always
    command: server /data --console-address ":9002"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio/data:/data # 映射文件路径