spring:
  application:
    name: simple-demo-cloud
  cloud:
    nacos:
      server-addr: http://127.0.0.1:8848
      username:
      password:
      discovery:
        enabled: true
        registerEnabled: true
        namespace:
      config:
        enabled: true
        namespace:
        file-extension: yml
        import-check:
          enabled: false
  config:
    import:
      - optional:nacos:application.yml
      - optional:nacos:simple-demo-cloud.yml?group=DEFAULT_GROUP&refreshEnabled=false