server:
  port: 11050
spring:
  application:
    name: simple-demo-socket-two
simple:
  ## 无Redis配置情况下，默认开启Socket单机
  redisson:
    enabled: true
    type:  standalone
    address:  127.0.0.1:6379
    password: password
    database: 0
  socket:
    #缺省项为false
    enabled: true
    port: 12020
    upgradeTimeout: 1000000
    pingTimeout: 6000000
    pingInterval: 25000