server:
  port: 11050
spring:
  application:
    name: simple-demo-socket-two
simple:
  ## 无Redis配置情况下，默认开启Socket单机
  redisson:
    enabled: true
    type: standalone
    config:
      ## 单体模式
      standalone:
        address: redis://127.0.0.1:6379
        password:
        database: 0
  socket:
    #缺省项为false
    enabled: true
    port: 12020
    upgradeTimeout: 1000000
    pingTimeout: 6000000
    pingInterval: 25000