server:
  port: 11070
spring:
  application:
    name: simple-demo-grpc-client
simple:
  grpc:
    client:
      enabled: true
      channel:
        grpc-server-hello:
          address: '127.0.0.1:12030'
        grpc-server-person:
          address: '127.0.0.1:12030'