server:
  port: 13030
spring:
  application:
    name: demo-base-s3
simple:
  scan:
    ## 关闭service依赖中service服务端，仅使用service依赖中的api客户端
    service:
      enabled: false
  feign:
    # 开启日志记录，缺省默认开启
    logger:
      enabled: true
    base:
      s3:
        # 未开启注册中心需要指定调用地址
        url: http://localhost:9020
  s3:
    #缺省项为false
    enabled: true
    accessKey: RKcxrJ80qTgziqaH
    secretKey: pVlB5bm0vIA6aidjWLG8ZfKUIuB7dNUC
    endpoint: 127.0.0.1:9000

logging:
  level:
    # 声明包位置的Feign日志级别为debug，打印日志详情
    cn:
      iosd: debug