server:
  port: 13010

spring:
  application:
    name: demo-base-param
  datasource:
    mysql:
      master:
        database: simple_demo
simple:
  base:
    param:
      ##开启参数配置服务 缺省项为true
      enabled: true
