## 可共享配置
spring:
  cloud:
    nacos:
      server-addr: http://127.0.0.1:8848
      username:
      password:
      discovery:
        # 默认不需要服务发现
        enabled: false
        registerEnabled: true
        namespace:
      config:
        # 默认不需要配置中心
        enabled: false
        namespace:
        file-extension: yml
        import-check:
          enabled: false
#  可写出配置中心使用到的文件
#  config:
#    import:
#      - nacos:application.yml
#      - nacos:simple-base-s3-service.yml?group=DEFAULT_GROUP&refreshEnabled=false