version: '3.1'
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs